// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRfLXkEwiTR0fHbLQ6z9zikl7dqvTWbJU',
    appId: '1:1039476326950:web:0ba5f1ba05d75299dc5ce7',
    messagingSenderId: '1039476326950',
    projectId: 'crafting-custom-woodword',
    authDomain: 'crafting-custom-woodword.firebaseapp.com',
    storageBucket: 'crafting-custom-woodword.firebasestorage.app',
    measurementId: 'G-7QDYSCHL9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlKC2yXT5fsWHyF78JGP6Qn2fEwwPiemA',
    appId: '1:1039476326950:android:f5588f4d75d96ee1dc5ce7',
    messagingSenderId: '1039476326950',
    projectId: 'crafting-custom-woodword',
    storageBucket: 'crafting-custom-woodword.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaj_TfruiylK8rg0li_PSDWhZ_EcfpUDc',
    appId: '1:1039476326950:ios:33c551eaeaec2b4ddc5ce7',
    messagingSenderId: '1039476326950',
    projectId: 'crafting-custom-woodword',
    storageBucket: 'crafting-custom-woodword.firebasestorage.app',
    iosBundleId: 'com.craftingcustomwoodworks.www.craftingCustomWoodworks',
  );
}
